### ISSUE TITLE
Criar caderno de testes

### ISSUE THREAD

**Issue by ZaqueuCavalcante** [NR-Mech/IntegraMech#34]
- [ ] Inserir no site

**Comment by GuttoF** [comment]
[https://docs.google.com/document/d/1MX0dWzvjyhZZh9ioyFhM5gvi44M_LhhRGM7SIOXxHqI/edit](caderno de testes v1)

**Comment by GuttoF** [comment]
### V1
Caderno de testes disponível em: https://docs.google.com/document/d/1MX0dWzvjyhZZh9ioyFhM5gvi44M_LhhRGM7SIOXxHqI/edit
